### ISSUE TITLE
Platform Support

### ISSUE THREAD

**Issue by jalcine** [kevva/wifi-name#2]
Something like this is named _very_ abstractly and gives the impression that it's platform-agnostic. Mind mentioning platform support on the landing page? :+1:

**Comment by kevva** [comment]
@jalcine, I'll add Windows support very soon. See #1.

**Comment by jalcine** [comment]
Heh, not a Windows user :smirk: but thanks nonetheless!

**Comment by kevva** [comment]
@jalcine, what Linux distro are you running? Or something other platform?

**Comment by jalcine** [comment]
`nmcli` is a very popular tool for network management but relying on it might be too biased. A more universal tool would be using `iwconfig`. 

I'm a Ubuntu user but I switch between Arch using `wicd` (which doesn't have `nmcli`).

**Comment by kevva** [comment]
I think https://github.com/kevva/wifi-name/commit/95a7092d20963a4cb196aac8a9c3f2b70ce5e00a fixed this since `iwgetid` is more widely supported.

**Comment by jalcine** [comment]
Oh definitely! Very good choice :8ball:
