### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by welcoMattic** [kevva/wifi-name#3]
Hello,

I just install globally `wifi-name` package, and I catch this error message : 

```
env: node\r: No such file or directory
```

My node env: 
OS : OS X 10.10.2
`node -v` : 0.12.0
`npm -v` : 2.7.0
`which node` : `/usr/local/bin/node`

Thanks for your work ! ;)

**Comment by roman01la** [comment]
+1

**Comment by kevva** [comment]
Try installing 1.0.7.

**Comment by roman01la** [comment]
Now it works, thanks :+1:
