### ISSUE TITLE
Throw a specific error when wifi is not actived

### ISSUE THREAD

**Issue by Manu1400** [kevva/wifi-name#8]
1/ On Mac, disable wifi
2/ run the example of README

The error return : 
`(node:27211) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not get SSID`

expectation : return a specific error (Error: Wifi disabled. Can get SSID.)

**Comment by kevva** [comment]
Thanks for reporting. I've published a new release with a fix.
